//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCdbdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class model
    {
        public int modelID { get; set; }
        public string modelName { get; set; }
        public int companyID { get; set; }
    
        public virtual company company { get; set; }
    }
}
